name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the base Docker image
      run: cd package/docker/src/main/resources/docker/base && docker build . --file Dockerfile --tag maximilianvoss/musicsyncbase:latest
    - name: Build the app Docker image
      run: cd package/docker/src/main/resources/docker/application && docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    - name: Push the docker  image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
